### ISSUE TITLE
There is no dll file in the package.

### ISSUE THREAD

**Issue by infatum1** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#2]
- Put the DLL in the <Paint.NET>\FileTypes directory (default location is C:\Program Files\paint.net\FileTypes)
For the Windows Store version of Paint.NET, put the DLL in the <Documents>\paint.net App Files\FileTypes directory

**Comment by otuncelli** [comment]
You can download it from the releases section.

https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/releases

**Comment by infatum1** [comment]
Thanks, but Paint.net version 4.0.19. has shown this while trying to open an svg:

System.FormatException: Input string was not in a correct format.

   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)

   at System.Convert.ToSingle(String value)

   at ControlExtensions.ImSvg.Meal.EatNumber(Single& number)

   at ControlExtensions.ImSvg.BasicTypeLength(SvgEnvironment env, XmlNode elementNode, String attributeName, SvgDirectionEnum direction, Single lacunaValue)

   at ControlExtensions.ImSvg.ShapeRect..ctor(SvgEnvironment env, XmlNode elementNode)

   at ControlExtensions.ImSvg.ElementRect(Graphics g, XmlNode elementNode)

   at ControlExtensions.ImSvg.ElementNode(Graphics g, XmlNode elementNode, Int32 depth)

   at ControlExtensions.ImSvg.ElementG(Graphics g, XmlNode elementNode, Int32 depth)

   at ControlExtensions.ImSvg.ElementNode(Graphics g, XmlNode elementNode, Int32 depth)

   at ControlExtensions.ImSvg.ElementSvg(Graphics g, XmlNode svgElementNode, Int32 depth)

   at OptionBasedFileTypes.SvgFileType.OnLoad(Stream input)

   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src\Data\FileType.cs:line 496

   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src\Base\Functional\Func.cs:line 158
